### ISSUE TITLE
Collecting backlog.

### ISSUE THREAD

**Issue by melodykramer** [18F/projects#15]
We're starting to come up with really good ideas for the dashboard and I want to ensure that we're capturing our backlog. Should we use the Wiki? Issues, tagged in a certain way? Trello? Something else?

**Comment by brendansudol** [comment]
Do you have a preference? I'm open :)

**Comment by melodykramer** [comment]
Let's do issues, tagged "backlog"

**Comment by toolness** [comment]
Cool, sounds good! Since this issue seems to be resolved now, I'm closing it, but feel free to re-open if I'm misinterpreting things.
