### ISSUE TITLE
Create a script that imports existing projects into the database

### ISSUE THREAD

**Issue by toolness** [18F/projects#6]
I believe there exists somewhere on the internet a list of all current 18F projects. It is probably in YAML, but I'm not sure where it is.

I'm realizing as I work on #5 that it would help me immensely to see this list, so that I can better figure out what the `Project` model should look like.

@brendansudol or @melodykramer, any idea where this list of projects is?

**Comment by brendansudol** [comment]
I think that google spreadsheet that @melodykramer has been working on is the best bet here (which we can clean up and convert to json before importing)

**Comment by brendansudol** [comment]
also, check out this entry (and parent folder) - https://github.com/18F/18f.gsa.gov/blob/dashboard/_data/dashboard/college-choice.yml

**Comment by melodykramer** [comment]
The google spreadsheet is where I've been working.
