### ISSUE TITLE
autocomplete for client names

### ISSUE THREAD

**Issue by batemapf** [18F/projects#8]
we have 350+ possibilities for client names. maybe add an autocomplete to the admin panel like https://bitbucket.org/tyrion/django-autocomplete/wiki/Home?

**Comment by toolness** [comment]
So I did a bit of research on autocomplete packages and I noticed that `django-autocomplete`'s home page says:

> It's not really stable yet, and some things could change!

Which worries me a bit. On the other hand, [`django-autocomplete-light`](https://github.com/yourlabs/django-autocomplete-light) claims to be stable, even has a test API to make writing unit tests easy, and has had commits in the past 2 weeks, so it appears to be maintained. So I'm leaning towards using that one.
